name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./target/release/aes

  build_on_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./target/release/aes.exe

  build_on_macos:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./target/release/aes
